version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${SPRING_DATASORUCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASORUCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASORUCE_DB}
    ports:
      - "5433:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data